#ifndef _predX_var_H
#define _predX_var_H

#include <RcppArmadillo.h>

RcppExport SEXP EXPSMOOTH1(SEXP Y, SEXP PARAM, SEXP STARTVAL, SEXP NOUT) ;
RcppExport SEXP EXPSMOOTH2(SEXP Y, SEXP PARAM, SEXP THOLD, SEXP STARTVAL, SEXP NOUT) ;
RcppExport SEXP EXPSMOOTH3(SEXP Y, SEXP PARAM, SEXP STARTVAL, SEXP NOUT) ;

RcppExport SEXP SEASEXPSMOOTH(SEXP Y, SEXP S, SEXP PARAM, SEXP STARTVAL, SEXP NOUT) ;
RcppExport SEXP SIMDAYEXPSMOOTH(SEXP Y, SEXP DAYS, SEXP S, SEXP PARAM, SEXP STARTVAL) ;
RcppExport SEXP RMSIMDAYEXPSMOOTH(SEXP Y, SEXP DAYS, SEXP S, SEXP PARAM, SEXP THOLD, SEXP STARTVAL) ;

RcppExport SEXP SIMDAYSMOOTH(SEXP Y, SEXP DAYS, SEXP S, SEXP OPTNOUT, SEXP PARAM, SEXP THOLD, SEXP STARTVAL) ;
RcppExport SEXP SIMDAYSMOOTHLEVELINPUT(SEXP Y, SEXP L, SEXP DAYS, SEXP S, SEXP OPTNOUT, SEXP PARAM, SEXP THOLD, SEXP STARTVAL) ;



#endif
